//! v23: permanent per-credential daily usage and quota-window cycle history.

pub const SQLITE_SQL: &[&str] = &[
    "CREATE TABLE IF NOT EXISTS credential_usage_daily (\
        id INTEGER PRIMARY KEY, day_start INTEGER NOT NULL, credential_id INTEGER NOT NULL, \
        provider_id INTEGER NOT NULL, model TEXT, requests INTEGER NOT NULL, \
        input_tokens INTEGER NOT NULL, output_tokens INTEGER NOT NULL, \
        image_output_tokens INTEGER NOT NULL, cache_read_tokens INTEGER NOT NULL, \
        cache_creation_5m_tokens INTEGER NOT NULL, cache_creation_30m_tokens INTEGER NOT NULL, \
        cache_creation_1h_tokens INTEGER NOT NULL, cost TEXT NOT NULL, \
        created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_credential_usage_daily_dims ON \
        credential_usage_daily (day_start, credential_id, COALESCE(model, ''))",
    "CREATE TABLE IF NOT EXISTS credential_quota_cycles (\
        id INTEGER PRIMARY KEY, credential_id INTEGER NOT NULL, provider_id INTEGER NOT NULL, \
        channel TEXT NOT NULL, window_key TEXT NOT NULL, name TEXT NOT NULL, label TEXT, \
        scope_kind TEXT NOT NULL, scope_json TEXT, meter_kind TEXT NOT NULL, \
        period_start INTEGER, period_end INTEGER, boundary_source TEXT NOT NULL, \
        boundary_confidence TEXT NOT NULL, close_reason TEXT, status TEXT NOT NULL, \
        open_slot INTEGER, last_observed_at INTEGER, used_percent TEXT, upstream_used TEXT, \
        upstream_limit TEXT, coverage TEXT NOT NULL, requests INTEGER NOT NULL, \
        input_tokens INTEGER NOT NULL, output_tokens INTEGER NOT NULL, \
        image_output_tokens INTEGER NOT NULL, cache_read_tokens INTEGER NOT NULL, \
        cache_creation_5m_tokens INTEGER NOT NULL, cache_creation_30m_tokens INTEGER NOT NULL, \
        cache_creation_1h_tokens INTEGER NOT NULL, cost TEXT NOT NULL, estimated_tokens INTEGER, \
        estimated_cost TEXT, aggregated_through INTEGER, finalized_at INTEGER, \
        created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_credential_quota_cycles_open ON \
        credential_quota_cycles (credential_id, window_key, open_slot)",
    "CREATE INDEX IF NOT EXISTS ix_credential_quota_cycles_history ON \
        credential_quota_cycles (credential_id, window_key, period_start)",
    "CREATE TABLE IF NOT EXISTS credential_quota_cycle_models (\
        id INTEGER PRIMARY KEY, cycle_id INTEGER NOT NULL, model TEXT NOT NULL, \
        requests INTEGER NOT NULL, input_tokens INTEGER NOT NULL, output_tokens INTEGER NOT NULL, \
        image_output_tokens INTEGER NOT NULL, cache_read_tokens INTEGER NOT NULL, \
        cache_creation_5m_tokens INTEGER NOT NULL, cache_creation_30m_tokens INTEGER NOT NULL, \
        cache_creation_1h_tokens INTEGER NOT NULL, cost TEXT NOT NULL, \
        created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_credential_quota_cycle_models_dims ON \
        credential_quota_cycle_models (cycle_id, model)",
    "INSERT OR IGNORE INTO credential_usage_daily (day_start, credential_id, provider_id, model, requests, \
        input_tokens, output_tokens, image_output_tokens, cache_read_tokens, \
        cache_creation_5m_tokens, cache_creation_30m_tokens, cache_creation_1h_tokens, cost, \
        created_at, updated_at) SELECT (at / 86400) * 86400, credential_id, MAX(provider_id), \
        NULLIF(TRIM(model), ''), \
        COUNT(*), SUM(input_tokens), SUM(output_tokens), SUM(image_output_tokens), \
        SUM(cache_read_tokens), SUM(cache_creation_5m_tokens), SUM(cache_creation_30m_tokens), \
        SUM(cache_creation_1h_tokens), '0', \
        MAX(created_at), MAX(updated_at) FROM usages \
        WHERE credential_id IS NOT NULL AND provider_id IS NOT NULL \
        GROUP BY (at / 86400) * 86400, credential_id, NULLIF(TRIM(model), '')",
];

pub const POSTGRES_SQL: &[&str] = &[
    "CREATE TABLE IF NOT EXISTS credential_usage_daily (\
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, day_start BIGINT NOT NULL, \
        credential_id BIGINT NOT NULL, provider_id BIGINT NOT NULL, model TEXT, \
        requests BIGINT NOT NULL, input_tokens BIGINT NOT NULL, output_tokens BIGINT NOT NULL, \
        image_output_tokens BIGINT NOT NULL, cache_read_tokens BIGINT NOT NULL, \
        cache_creation_5m_tokens BIGINT NOT NULL, cache_creation_30m_tokens BIGINT NOT NULL, \
        cache_creation_1h_tokens BIGINT NOT NULL, cost TEXT NOT NULL, \
        created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_credential_usage_daily_dims ON \
        credential_usage_daily (day_start, credential_id, COALESCE(model, ''))",
    "CREATE TABLE IF NOT EXISTS credential_quota_cycles (\
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, credential_id BIGINT NOT NULL, \
        provider_id BIGINT NOT NULL, channel TEXT NOT NULL, window_key TEXT NOT NULL, \
        name TEXT NOT NULL, label TEXT, scope_kind TEXT NOT NULL, scope_json TEXT, \
        meter_kind TEXT NOT NULL, period_start BIGINT, period_end BIGINT, \
        boundary_source TEXT NOT NULL, boundary_confidence TEXT NOT NULL, close_reason TEXT, \
        status TEXT NOT NULL, open_slot BIGINT, last_observed_at BIGINT, used_percent TEXT, \
        upstream_used TEXT, upstream_limit TEXT, coverage TEXT NOT NULL, requests BIGINT NOT NULL, \
        input_tokens BIGINT NOT NULL, output_tokens BIGINT NOT NULL, image_output_tokens BIGINT NOT NULL, \
        cache_read_tokens BIGINT NOT NULL, cache_creation_5m_tokens BIGINT NOT NULL, \
        cache_creation_30m_tokens BIGINT NOT NULL, cache_creation_1h_tokens BIGINT NOT NULL, \
        cost TEXT NOT NULL, estimated_tokens BIGINT, estimated_cost TEXT, aggregated_through BIGINT, \
        finalized_at BIGINT, created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_credential_quota_cycles_open ON \
        credential_quota_cycles (credential_id, window_key, open_slot)",
    "CREATE INDEX IF NOT EXISTS ix_credential_quota_cycles_history ON \
        credential_quota_cycles (credential_id, window_key, period_start)",
    "CREATE TABLE IF NOT EXISTS credential_quota_cycle_models (\
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cycle_id BIGINT NOT NULL, \
        model TEXT NOT NULL, requests BIGINT NOT NULL, input_tokens BIGINT NOT NULL, \
        output_tokens BIGINT NOT NULL, image_output_tokens BIGINT NOT NULL, \
        cache_read_tokens BIGINT NOT NULL, cache_creation_5m_tokens BIGINT NOT NULL, \
        cache_creation_30m_tokens BIGINT NOT NULL, cache_creation_1h_tokens BIGINT NOT NULL, \
        cost TEXT NOT NULL, created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_credential_quota_cycle_models_dims ON \
        credential_quota_cycle_models (cycle_id, model)",
    "INSERT INTO credential_usage_daily (day_start, credential_id, provider_id, model, requests, \
        input_tokens, output_tokens, image_output_tokens, cache_read_tokens, \
        cache_creation_5m_tokens, cache_creation_30m_tokens, cache_creation_1h_tokens, cost, \
        created_at, updated_at) SELECT (at / 86400) * 86400, credential_id, MAX(provider_id), \
        NULLIF(TRIM(model), ''), \
        COUNT(*), SUM(input_tokens), SUM(output_tokens), SUM(image_output_tokens), \
        SUM(cache_read_tokens), SUM(cache_creation_5m_tokens), SUM(cache_creation_30m_tokens), \
        SUM(cache_creation_1h_tokens), CAST(COALESCE(SUM(CAST(cost AS NUMERIC)), 0) AS TEXT), \
        MAX(created_at), MAX(updated_at) FROM usages \
        WHERE credential_id IS NOT NULL AND provider_id IS NOT NULL \
        GROUP BY (at / 86400) * 86400, credential_id, NULLIF(TRIM(model), '') \
        ON CONFLICT DO NOTHING",
];

pub const MYSQL_SQL: &[&str] = &[
    "CREATE TABLE IF NOT EXISTS credential_usage_daily (\
        id BIGINT NOT NULL AUTO_INCREMENT, day_start BIGINT NOT NULL, credential_id BIGINT NOT NULL, \
        provider_id BIGINT NOT NULL, model VARCHAR(255), requests BIGINT NOT NULL, \
        input_tokens BIGINT NOT NULL, output_tokens BIGINT NOT NULL, image_output_tokens BIGINT NOT NULL, \
        cache_read_tokens BIGINT NOT NULL, cache_creation_5m_tokens BIGINT NOT NULL, \
        cache_creation_30m_tokens BIGINT NOT NULL, cache_creation_1h_tokens BIGINT NOT NULL, \
        cost TEXT NOT NULL, created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL, PRIMARY KEY (id))",
    "CREATE UNIQUE INDEX uq_credential_usage_daily_dims ON credential_usage_daily \
        (day_start, credential_id, (COALESCE(model, '')))",
    "CREATE TABLE IF NOT EXISTS credential_quota_cycles (\
        id BIGINT NOT NULL AUTO_INCREMENT, credential_id BIGINT NOT NULL, provider_id BIGINT NOT NULL, \
        channel VARCHAR(255) NOT NULL, window_key VARCHAR(255) NOT NULL, name TEXT NOT NULL, label TEXT, \
        scope_kind VARCHAR(32) NOT NULL, scope_json TEXT, meter_kind VARCHAR(32) NOT NULL, \
        period_start BIGINT, period_end BIGINT, boundary_source VARCHAR(32) NOT NULL, \
        boundary_confidence VARCHAR(32) NOT NULL, close_reason VARCHAR(32), status VARCHAR(16) NOT NULL, \
        open_slot BIGINT, last_observed_at BIGINT, used_percent TEXT, upstream_used TEXT, \
        upstream_limit TEXT, coverage VARCHAR(32) NOT NULL, requests BIGINT NOT NULL, \
        input_tokens BIGINT NOT NULL, output_tokens BIGINT NOT NULL, image_output_tokens BIGINT NOT NULL, \
        cache_read_tokens BIGINT NOT NULL, cache_creation_5m_tokens BIGINT NOT NULL, \
        cache_creation_30m_tokens BIGINT NOT NULL, cache_creation_1h_tokens BIGINT NOT NULL, \
        cost TEXT NOT NULL, estimated_tokens BIGINT, estimated_cost TEXT, aggregated_through BIGINT, \
        finalized_at BIGINT, created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL, PRIMARY KEY (id))",
    "CREATE UNIQUE INDEX uq_credential_quota_cycles_open ON credential_quota_cycles \
        (credential_id, window_key, open_slot)",
    "CREATE INDEX ix_credential_quota_cycles_history ON credential_quota_cycles \
        (credential_id, window_key, period_start)",
    "CREATE TABLE IF NOT EXISTS credential_quota_cycle_models (\
        id BIGINT NOT NULL AUTO_INCREMENT, cycle_id BIGINT NOT NULL, model VARCHAR(255) NOT NULL, \
        requests BIGINT NOT NULL, input_tokens BIGINT NOT NULL, output_tokens BIGINT NOT NULL, \
        image_output_tokens BIGINT NOT NULL, cache_read_tokens BIGINT NOT NULL, \
        cache_creation_5m_tokens BIGINT NOT NULL, cache_creation_30m_tokens BIGINT NOT NULL, \
        cache_creation_1h_tokens BIGINT NOT NULL, cost TEXT NOT NULL, \
        created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL, PRIMARY KEY (id))",
    "CREATE UNIQUE INDEX uq_credential_quota_cycle_models_dims ON \
        credential_quota_cycle_models (cycle_id, model)",
    "INSERT IGNORE INTO credential_usage_daily (day_start, credential_id, provider_id, model, requests, \
        input_tokens, output_tokens, image_output_tokens, cache_read_tokens, \
        cache_creation_5m_tokens, cache_creation_30m_tokens, cache_creation_1h_tokens, cost, \
        created_at, updated_at) SELECT (at DIV 86400) * 86400, credential_id, MAX(provider_id), \
        NULLIF(TRIM(model), ''), \
        COUNT(*), SUM(input_tokens), SUM(output_tokens), SUM(image_output_tokens), \
        SUM(cache_read_tokens), SUM(cache_creation_5m_tokens), SUM(cache_creation_30m_tokens), \
        SUM(cache_creation_1h_tokens), \
        CAST(COALESCE(SUM(CAST(cost AS DECIMAL(65, 30))), 0) AS CHAR), \
        MAX(created_at), MAX(updated_at) FROM usages \
        WHERE credential_id IS NOT NULL AND provider_id IS NOT NULL \
        GROUP BY (at DIV 86400) * 86400, credential_id, NULLIF(TRIM(model), '')",
];
