//! images conversion family: OpenAI Images (`/v1/images/generations` and
//! `/v1/images/edits`) against an upstream that generates images through the
//! Responses API image tool or Gemini `generateContent`. One native call per
//! requested image; `adapt::images` never retries a possibly billed call.
//!
//! Deliberate boundaries:
//! * Only the OpenAI dialect has an images API, so that is the only client
//!   shape; Claude upstreams have no image generation and are refused.
//! * `response_format: url` needs the host's `PublicationUrl`
//!   (`CoreBuilder::publication_url`): generated bytes are stored through
//!   `Resources` and the host mints the link it serves them under. Without a
//!   link builder the request is refused before any upstream call; `b64_json`
//!   (the default) returns the bytes inline.
//! * Multipart edits become data URLs the adapter decodes inline; `file_id`
//!   references are read through `Resources`, so a file on the target provider
//!   or a body core published earlier can be edited.

use super::{Call, Converted};
use crate::{ExecutionTarget, ResourceScope, Resources};
use gproxy_protocol::{
    Dialect, HttpBody, Operation, OperationKey, WireResponse,
    adapt::images::{self as adapt, ImageError, ImageLimits, ImageProgress},
    capability::Upstream,
    codec::{
        CodecError, CodecErrorKind, CodecLimits, MultipartDecoder, decode_json, encode_json,
        read_http_body,
    },
    connection::Bytes,
    transform::{
        TransformError, TransformErrorKind,
        images::{ImageDialect, ImageInput, ImageResponseFacts, ImageTargetModels, inspect_image},
    },
    wire::openai::images as o,
};
use gproxy_seaorm::BatchConnectionTrait;
use http::{HeaderMap, HeaderValue, StatusCode};
use serde_json::{Map, Value};
use std::time::Duration;

/// OpenAI image URLs live for an hour; a published body would follow suit.
const PUBLISH_TTL: Duration = Duration::from_secs(60 * 60);
/// OpenAI accepts at most ten images per request.
const MAX_IMAGES: usize = 10;
/// Edits accept up to sixteen input images.
const MAX_INPUT_IMAGES: usize = 16;

fn codec(error: CodecError, context: &'static str) -> TransformError {
    let kind = match error.kind() {
        CodecErrorKind::Limit => TransformErrorKind::Limit,
        CodecErrorKind::Transport => TransformErrorKind::Host,
        _ => TransformErrorKind::InvalidInput,
    };
    TransformError::with_source(kind, context, error.to_string(), error)
}

fn boundary(headers: &HeaderMap) -> Option<String> {
    let content_type = headers
        .get(http::header::CONTENT_TYPE)
        .and_then(|v| v.to_str().ok())?;
    let mut parts = content_type.split(';');
    if !parts
        .next()
        .is_some_and(|m| m.trim().eq_ignore_ascii_case("multipart/form-data"))
    {
        return None;
    }
    parts
        .filter_map(|p| p.trim().split_once('='))
        .find(|(k, _)| k.trim().eq_ignore_ascii_case("boundary"))
        .map(|(_, v)| v.trim().trim_matches('"').to_owned())
        .filter(|b| !b.is_empty())
}

fn field_name(headers: &HeaderMap) -> Option<String> {
    headers
        .get(http::header::CONTENT_DISPOSITION)
        .and_then(|v| v.to_str().ok())?
        .split(';')
        .skip(1)
        .filter_map(|p| p.trim().split_once('='))
        .find(|(k, _)| k.trim() == "name")
        .map(|(_, v)| v.trim().trim_matches('"').to_owned())
}

/// One uploaded image as the data URL the adapter decodes inline. The MIME
/// comes from the bytes themselves; a declared type is checked against them.
fn data_url(headers: &HeaderMap, bytes: &[u8]) -> Result<String, TransformError> {
    let sniffed = inspect_image(bytes)?.mime();
    if let Some(declared) = headers
        .get(http::header::CONTENT_TYPE)
        .and_then(|v| v.to_str().ok())
        .map(|v| v.split(';').next().unwrap_or("").trim())
        .filter(|v| !v.is_empty())
        && !declared.eq_ignore_ascii_case(sniffed)
    {
        return Err(TransformError::shape(
            "image.part",
            "declared content-type contradicts the image bytes",
        ));
    }
    Ok(format!("data:{sniffed};base64,{}", base64_encode(bytes)))
}

fn base64_encode(bytes: &[u8]) -> String {
    use base64::Engine;
    base64::engine::general_purpose::STANDARD.encode(bytes)
}

/// The multipart edit form, re-expressed as the JSON edit body: image parts
/// become `image_url` data URLs, text parts keep their field names.
async fn multipart_edit<C: BatchConnectionTrait + Send + Sync>(
    call: &Call<'_, C>,
    boundary: String,
) -> Result<o::EditImageJsonBody, TransformError> {
    let body = HttpBody::Bytes(Bytes::copy_from_slice(call.body()));
    let mut decoder =
        MultipartDecoder::new(body, boundary, call.limits).map_err(|e| codec(e, "image.form"))?;
    let mut part_limits = call.limits;
    part_limits.max_body_bytes = part_limits.max_body_bytes.min(part_limits.max_part_bytes);
    let mut fields = Map::new();
    let mut images = Vec::new();
    let mut mask = None;
    while let Some(part) = decoder
        .next_part()
        .await
        .map_err(|e| codec(e, "image.form"))?
    {
        let name = field_name(&part.headers)
            .ok_or_else(|| TransformError::shape("image.form", "part without a field name"))?;
        let bytes = read_http_body(part.body, part_limits)
            .await
            .map_err(|e| codec(e, "image.form"))?;
        match name.as_str() {
            "image" | "image[]" => {
                if images.len() >= MAX_INPUT_IMAGES {
                    return Err(TransformError::new(
                        TransformErrorKind::Limit,
                        "image.form",
                        "too many input images",
                    ));
                }
                images.push(serde_json::json!({ "image_url": data_url(&part.headers, &bytes)? }));
            }
            "mask" => {
                if mask.is_some() {
                    return Err(TransformError::shape("image.form", "duplicate mask part"));
                }
                mask = Some(serde_json::json!({ "image_url": data_url(&part.headers, &bytes)? }));
            }
            _ => {
                let text = String::from_utf8(bytes.to_vec())
                    .map_err(|_| TransformError::shape("image.form", "text field is not UTF-8"))?;
                let value = match name.as_str() {
                    "n" | "output_compression" | "partial_images" => {
                        text.trim().parse::<i64>().map(Value::from).map_err(|_| {
                            TransformError::shape("image.form", "integer field expected")
                        })?
                    }
                    "stream" => match text.trim() {
                        "true" => Value::Bool(true),
                        "false" => Value::Bool(false),
                        _ => {
                            return Err(TransformError::shape(
                                "image.form",
                                "boolean field expected",
                            ));
                        }
                    },
                    _ => Value::String(text),
                };
                fields.insert(name, value);
            }
        }
    }
    if images.is_empty() {
        return Err(TransformError::shape("image.form", "`image` part required"));
    }
    fields.insert("images".into(), Value::Array(images));
    if let Some(mask) = mask {
        fields.insert("mask".into(), mask);
    }
    serde_json::from_value(Value::Object(fields))
        .map_err(|e| TransformError::shape("image.form", e.to_string()))
}

fn json_response<T: serde::Serialize>(
    value: &T,
    limits: CodecLimits,
) -> Result<Converted, TransformError> {
    let body = encode_json(value, limits).map_err(|e| codec(e, "client.response"))?;
    let mut headers = HeaderMap::new();
    headers.insert(
        http::header::CONTENT_TYPE,
        HeaderValue::from_static("application/json"),
    );
    Ok(Converted::Success(WireResponse {
        status: StatusCode::OK,
        headers,
        body: HttpBody::Bytes(body),
    }))
}

fn requested_format(input: &ImageInput) -> Option<o::ImageResponseFormat> {
    match input {
        ImageInput::Create(v) => v.response_format.flatten(),
        ImageInput::Edit(_) => None,
        #[allow(unreachable_patterns)]
        _ => None,
    }
}

pub(crate) async fn run<C: BatchConnectionTrait + Send + Sync>(
    call: &Call<'_, C>,
) -> Result<Converted, TransformError> {
    if !matches!(call.client.dialect, Dialect::OpenAi | Dialect::OpenAiChat) {
        return Err(TransformError::unsupported(
            "images",
            format!("{:?} has no images API", call.client.dialect),
        ));
    }
    let dialect = match call.target {
        Dialect::OpenAi | Dialect::OpenAiChat => ImageDialect::Responses,
        Dialect::Gemini => ImageDialect::Gemini,
        Dialect::Claude | Dialect::OpenAiResponsesWebSocket => {
            return Err(TransformError::unsupported(
                "images",
                format!("{:?} has no image generation API", call.target),
            ));
        }
    };
    let input = match call.client.operation {
        Operation::CreateImage => ImageInput::Create(
            decode_json::<o::CreateImageRequestBody>(call.body(), call.limits)
                .map_err(|e| codec(e, "client.body"))?,
        ),
        Operation::EditImage => ImageInput::Edit(match boundary(call.request.headers) {
            Some(boundary) => multipart_edit(call, boundary).await?,
            None => decode_json::<o::EditImageJsonBody>(call.body(), call.limits)
                .map_err(|e| codec(e, "client.body"))?,
        }),
        other => {
            return Err(TransformError::unsupported(
                "images",
                format!("{other:?} is not an images operation"),
            ));
        }
    };
    // The adapt flow publishes only after generation; refuse here so a host
    // without a link builder never pays for images it cannot deliver.
    if requested_format(&input) == Some(o::ImageResponseFormat::Url)
        && call.core.publication_url().is_none()
    {
        return Err(TransformError::unsupported(
            "image.response_format",
            "core publishes no URLs: host configured no PublicationUrl; request b64_json",
        ));
    }
    let models = ImageTargetModels {
        generation_model: call.model()?.to_owned(),
        image_tool_model: None,
    };
    let attempt = call.upstream.attempt();
    let facts = ImageResponseFacts {
        created: call.now_ms.div_euclid(1000),
        observed_at: call.now(),
        default_response_format: o::ImageResponseFormat::B64Json,
        publish_expires_at: Some(call.now() + PUBLISH_TTL),
        operation_id: attempt.attempt_id.clone(),
    };
    let limits = ImageLimits {
        codec: call.limits,
        max_calls: MAX_IMAGES,
        max_input_images: MAX_INPUT_IMAGES,
        max_input_bytes: call.limits.max_part_bytes,
        max_total_input_bytes: call.limits.max_body_bytes,
        max_output_bytes: call.limits.max_body_bytes,
        max_total_output_bytes: call.limits.max_body_bytes,
    };
    let core = call.core;
    let resources = Resources::new(core, call.upstream.limits(), call.limits);
    let target = &attempt.request.target;
    let scope = ResourceScope {
        scope: call.state_scope.scope.clone(),
        target: ExecutionTarget {
            provider: target.provider.clone(),
            upstream_model: target.upstream_model.clone(),
            credentials: target.credentials.clone(),
        },
    };
    let key = OperationKey {
        operation: Operation::GenerateContent,
        dialect: call.target,
    };
    let mut progress = ImageProgress::default();
    match adapt::generate(
        &resources,
        &scope,
        call.upstream,
        &key,
        input,
        dialect,
        &models,
        &facts,
        limits,
        &mut progress,
    )
    .await
    {
        Ok(outcome) => json_response(&outcome.response, call.limits),
        Err(ImageError::Rejected(response)) => Ok(Converted::Rejected(*response)),
        Err(ImageError::Transform(error)) => Err(error),
        Err(
            ImageError::InvalidResponses { error, .. } | ImageError::InvalidGemini { error, .. },
        ) => Err(error),
        #[allow(unreachable_patterns)]
        Err(other) => Err(TransformError::invalid_result("images", other.to_string())),
    }
}
