use serde::{Deserialize, Serialize};

use crate::providers::credential_status::ProviderKind;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsageRecord {
    pub provider: ProviderKind,
    pub caller_api_key: Option<String>,
    pub provider_credential_id: Option<String>,
    pub model: Option<String>,
    pub upstream_model: Option<String>,
    pub format: Option<String>,
    pub request_id: Option<String>,
    pub created_at: i64,
    pub oa_resp_input_tokens: Option<i64>,
    pub oa_resp_output_tokens: Option<i64>,
    pub oa_resp_total_tokens: Option<i64>,
    pub oa_resp_input_tokens_details_cached_tokens: Option<i64>,
    pub oa_resp_output_tokens_details_reasoning_tokens: Option<i64>,
    pub oa_resp_output_tokens_details_audio_tokens: Option<i64>,
    pub oa_resp_output_tokens_details_cached_tokens: Option<i64>,
    pub oa_chat_prompt_tokens: Option<i64>,
    pub oa_chat_completion_tokens: Option<i64>,
    pub oa_chat_total_tokens: Option<i64>,
    pub oa_chat_prompt_tokens_details_cached_tokens: Option<i64>,
    pub oa_chat_completion_tokens_details_reasoning_tokens: Option<i64>,
    pub oa_chat_completion_tokens_details_audio_tokens: Option<i64>,
    pub claude_input_tokens: Option<i64>,
    pub claude_output_tokens: Option<i64>,
    pub claude_cache_creation_input_tokens: Option<i64>,
    pub claude_cache_read_input_tokens: Option<i64>,
    pub gemini_prompt_token_count: Option<i64>,
    pub gemini_candidates_token_count: Option<i64>,
    pub gemini_total_token_count: Option<i64>,
    pub gemini_cached_content_token_count: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsageViewRecord {
    pub view_name: String,
    pub anchor_ts: i64,
    pub slot_start: i64,
    pub provider: ProviderKind,
    pub caller_api_key: Option<String>,
    pub provider_credential_id: Option<String>,
    pub model: Option<String>,
    pub upstream_model: Option<String>,
    pub format: Option<String>,
    pub record_count: i64,
    pub oa_resp_input_tokens_sum: i64,
    pub oa_resp_output_tokens_sum: i64,
    pub oa_resp_total_tokens_sum: i64,
    pub oa_resp_input_tokens_details_cached_tokens_sum: i64,
    pub oa_resp_output_tokens_details_reasoning_tokens_sum: i64,
    pub oa_resp_output_tokens_details_audio_tokens_sum: i64,
    pub oa_resp_output_tokens_details_cached_tokens_sum: i64,
    pub oa_chat_prompt_tokens_sum: i64,
    pub oa_chat_completion_tokens_sum: i64,
    pub oa_chat_total_tokens_sum: i64,
    pub oa_chat_prompt_tokens_details_cached_tokens_sum: i64,
    pub oa_chat_completion_tokens_details_reasoning_tokens_sum: i64,
    pub oa_chat_completion_tokens_details_audio_tokens_sum: i64,
    pub claude_input_tokens_sum: i64,
    pub claude_output_tokens_sum: i64,
    pub claude_cache_creation_input_tokens_sum: i64,
    pub claude_cache_read_input_tokens_sum: i64,
    pub gemini_prompt_token_count_sum: i64,
    pub gemini_candidates_token_count_sum: i64,
    pub gemini_total_token_count_sum: i64,
    pub gemini_cached_content_token_count_sum: i64,
}
