mod dispatch;
mod resolve;

pub(crate) use dispatch::{request, response};
pub(crate) use resolve::resolve;

#[derive(Clone, Copy)]
pub(crate) enum TransformPair {
    OpenAiModelsToClaude,
    ClaudeModelsToOpenAi,
    OpenAiModelsToGemini,
    GeminiModelsToOpenAi,
    ClaudeModelsToGemini,
    GeminiModelsToClaude,
    OpenAiCountToClaude,
    ClaudeCountToOpenAi,
    OpenAiCountToGemini,
    GeminiCountToOpenAi,
    ClaudeCountToGemini,
    GeminiCountToClaude,
    ChatToClaude,
    ClaudeToChat,
    ResponsesToClaude,
    ClaudeToResponses,
    ClaudeToGemini,
    GeminiToClaude,
    GeminiToChat,
    ChatToGemini,
    GeminiToResponses,
    ResponsesToGemini,
    OpenAiChatToResponses,
    OpenAiResponsesToChat,
    CompactToClaude,
    CompactToResponses,
    CompactToGemini,
    CompactToChat,
    ResponsesToCompact,
    GeminiToCompact,
    ChatToCompact,
    ClaudeToCompact,
    OpenAiEmbeddingToGemini,
    OpenAiEmbeddingToGeminiBatch,
    GeminiEmbeddingToOpenAi,
    GeminiBatchEmbeddingToOpenAi,
    OpenAiCreateImageToGemini,
    GeminiToOpenAiCreateImage,
    OpenAiEditImageToGemini,
    GeminiToOpenAiEditImage,
    OpenAiCreateImageToResponses,
    ResponsesToOpenAiCreateImage,
    OpenAiEditImageToResponses,
    ResponsesToOpenAiEditImage,
    OpenAiCreateImageToImagen,
    ImagenToOpenAiCreateImage,
    OpenAiVideoToGemini,
    GeminiVideoToOpenAi,
}
