use super::super::{
    ColumnKind::*, ColumnSpec as Col, IndexSpec, Ownership, SchemaVersion, TableSpec,
};

pub(super) const TABLES: &[TableSpec] = &[
    TableSpec {
        version: SchemaVersion::Initial,
        name: "usage_rows",
        columns: &[
            Col::id(),
            Col::optional("upstream_started_at_ms", Integer),
            Col::required("request_id", Text).unique(),
            Col::required("at", Integer),
            Col::required("provider_id", Integer),
            Col::required("credential_id", Integer),
            Col::optional("organization_id", Integer),
            Col::optional("team_id", Integer),
            Col::optional("user_id", Integer),
            Col::optional("user_key_id", Integer),
            Col::optional("operation", Text),
            Col::required("upstream_model", Text),
            Col::required("input_tokens", Integer),
            Col::required("output_tokens", Integer),
            Col::required("cached_input_tokens", Integer),
            Col::required("metrics_json", Text),
            Col::required("dimensions_json", Text),
            Col::required("cost", Text),
            Col::required("usage_source", Text),
            Col::required("ended", Text),
            Col::required("latency_ms", Integer),
        ],
        owns: &[Ownership::Owns {
            table: "credential_quota_cycle_usage",
            column: "usage_id",
        }],
        indexes: &[
            IndexSpec {
                name: "ix_usage_rows_credential_started",
                columns: &["credential_id", "upstream_started_at_ms", "id"],
                unique: false,
                added_in: None,
            },
            IndexSpec {
                name: "ix_usage_rows_user_provider_at",
                columns: &["user_id", "provider_id", "at", "id"],
                unique: false,
                added_in: None,
            },
            IndexSpec {
                name: "ix_usage_rows_credential_at",
                columns: &["credential_id", "at", "id"],
                unique: false,
                added_in: None,
            },
            IndexSpec {
                name: "ix_usage_rows_at",
                columns: &["at", "id"],
                unique: false,
                added_in: None,
            },
            IndexSpec {
                name: "ix_usage_rows_key_at",
                columns: &["user_key_id", "at", "id"],
                unique: false,
                added_in: None,
            },
            IndexSpec {
                name: "ix_usage_rows_user_at",
                columns: &["user_id", "at", "id"],
                unique: false,
                added_in: None,
            },
            IndexSpec {
                name: "ix_usage_rows_provider_at",
                columns: &["provider_id", "at", "id"],
                unique: false,
                added_in: None,
            },
            IndexSpec {
                name: "ix_usage_rows_model_at",
                columns: &["upstream_model", "at", "id"],
                unique: false,
                added_in: None,
            },
        ],
    },
    TableSpec {
        version: SchemaVersion::Initial,
        name: "usage_rollups",
        columns: &[
            Col::id(),
            Col::required("granularity", Text),
            Col::required("bucket_start", Integer),
            Col::required("dimension_key", Text),
            Col::optional("provider_id", Integer),
            Col::optional("organization_id", Integer),
            Col::optional("team_id", Integer),
            Col::optional("user_id", Integer),
            Col::optional("upstream_model", Text),
            Col::required("requests", Integer),
            Col::required("input_tokens", Integer),
            Col::required("output_tokens", Integer),
            Col::required("cached_input_tokens", Integer),
            Col::required("metrics_json", Text),
            Col::required("cost", Text),
            Col::required("version", Integer),
        ],
        owns: &[],
        indexes: &[
            IndexSpec {
                name: "uq_usage_rollups_bucket",
                columns: &["granularity", "bucket_start", "dimension_key"],
                unique: true,
                added_in: None,
            },
            IndexSpec {
                name: "ix_usage_rollups_user_provider_bucket",
                columns: &["user_id", "provider_id", "bucket_start"],
                unique: false,
                added_in: None,
            },
        ],
    },
];
