use gproxy_channel_api::ChannelSupport;

use crate::shared::routing::route;

pub(super) static ROUTES: &[ChannelSupport] = &[
    route!(pass ListModels, openai),
    route!(pass ListModels, claude),
    route!(pass ListModels, gemini),
    route!(pass GetModel, openai),
    route!(pass GetModel, claude),
    route!(pass GetModel, gemini),
    route!(pass CountTokens, openai),
    route!(pass CountTokens, claude),
    route!(pass CountTokens, gemini),
    route!(pass GenerateContent, openai_responses),
    route!(pass GenerateContent, openai_chat),
    route!(pass GenerateContent, claude_messages),
    route!(pass GenerateContent, gemini_generate_content),
    route!(pass StreamGenerateContent, openai_responses),
    route!(pass StreamGenerateContent, openai_chat),
    route!(pass StreamGenerateContent, claude_messages),
    route!(pass StreamGenerateContent, gemini_generate_content),
    route!(pass CreateEmbedding, openai),
    route!(pass CreateEmbedding, claude),
    route!(pass CreateEmbedding, gemini),
    route!(pass Rerank, openai),
    route!(pass CreateSpeech, openai),
    route!(pass CreateTranscription, openai),
    route!(pass CreateTranslation, openai),
    route!(pass CreateImage, openai),
    route!(pass CreateImage, claude),
    route!(pass CreateImage, gemini),
    route!(pass EditImage, openai),
    route!(pass EditImage, claude),
    route!(pass EditImage, gemini),
    route!(pass CreateVideo, openai),
    route!(pass RetrieveVideo, openai),
    route!(pass ListVideos, openai),
    route!(pass DeleteVideo, openai),
    route!(pass DownloadVideoContent, openai),
    route!(pass RemixVideo, openai),
    route!(pass CreateVideoCharacter, openai),
    route!(pass GetVideoCharacter, openai),
    route!(pass EditVideo, openai),
    route!(pass ExtendVideo, openai),
    route!(pass CompactContent, openai),
    route!(pass CompactContent, claude),
    route!(pass CompactContent, gemini),
];
