use super::{ColumnKind::*, ColumnSpec as Col, IndexSpec, SchemaVersion, TableSpec};

pub const TABLES: &[TableSpec] = &[
    TableSpec {
        version: SchemaVersion::Runtime,
        name: "quota_windows",
        columns: &[
            Col::id(),
            Col::required("quota_id", Integer),
            Col::required("window_start", Integer),
            Col::required("used_tokens", Integer),
        ],
        indexes: &[IndexSpec {
            name: "uq_quota_windows_period",
            columns: &["quota_id", "window_start"],
            unique: true,
        }],
    },
    TableSpec {
        version: SchemaVersion::Runtime,
        name: "usage_rows",
        columns: &[
            Col::id(),
            Col::required("request_id", Text).unique(),
            Col::required("at", Integer),
            Col::required("provider_id", Integer),
            Col::required("credential_id", Integer),
            Col::optional("organization_id", Integer),
            Col::optional("team_id", Integer),
            Col::optional("user_id", Integer),
            Col::optional("user_key_id", Integer),
            Col::optional("operation", Text),
            Col::required("upstream_model", Text),
            Col::required("input_tokens", Integer),
            Col::required("output_tokens", Integer),
            Col::required("cached_input_tokens", Integer),
            Col::required("metrics_json", Text),
            Col::required("dimensions_json", Text),
            Col::required("cost", Text),
            Col::required("usage_source", Text),
            Col::required("ended", Text),
            Col::required("latency_ms", Integer),
        ],
        indexes: &[
            IndexSpec {
                name: "ix_usage_rows_user_provider_at",
                columns: &["user_id", "provider_id", "at", "id"],
                unique: false,
            },
            IndexSpec {
                name: "ix_usage_rows_credential_at",
                columns: &["credential_id", "at", "id"],
                unique: false,
            },
        ],
    },
    TableSpec {
        version: SchemaVersion::Runtime,
        name: "usage_rollups",
        columns: &[
            Col::id(),
            Col::required("granularity", Text),
            Col::required("bucket_start", Integer),
            Col::required("dimension_key", Text),
            Col::optional("provider_id", Integer),
            Col::optional("organization_id", Integer),
            Col::optional("team_id", Integer),
            Col::optional("user_id", Integer),
            Col::optional("upstream_model", Text),
            Col::required("requests", Integer),
            Col::required("input_tokens", Integer),
            Col::required("output_tokens", Integer),
            Col::required("cached_input_tokens", Integer),
            Col::required("metrics_json", Text),
            Col::required("cost", Text),
            Col::required("version", Integer),
        ],
        indexes: &[
            IndexSpec {
                name: "uq_usage_rollups_bucket",
                columns: &["granularity", "bucket_start", "dimension_key"],
                unique: true,
            },
            IndexSpec {
                name: "ix_usage_rollups_user_provider_bucket",
                columns: &["user_id", "provider_id", "bucket_start"],
                unique: false,
            },
        ],
    },
    TableSpec {
        version: SchemaVersion::Runtime,
        name: "request_logs",
        columns: &[
            Col::id(),
            Col::required("request_id", Text).unique(),
            Col::required("at", Integer),
            Col::required("method", Text),
            Col::required("path", Text),
            Col::optional("query", Text),
            Col::optional("response_status", Integer),
            Col::optional("error_kind", Text),
        ],
        indexes: &[IndexSpec {
            name: "ix_request_logs_at",
            columns: &["at", "id"],
            unique: false,
        }],
    },
    TableSpec {
        version: SchemaVersion::Runtime,
        name: "wire_logs",
        columns: &[
            Col::id(),
            Col::required("request_id", Text),
            Col::required("at", Integer),
            Col::optional("provider_id", Integer),
            Col::optional("credential_id", Integer),
            Col::optional("upstream_url", Text),
            Col::optional("response_status", Integer),
            Col::required("request_body", Blob),
            Col::optional("response_body", Blob),
        ],
        indexes: &[IndexSpec {
            name: "ix_wire_logs_request",
            columns: &["request_id", "id"],
            unique: false,
        }],
    },
    TableSpec {
        version: SchemaVersion::Runtime,
        name: "surface_bindings",
        columns: &[
            Col::id(),
            Col::required("provider_id", Integer),
            Col::required("owner_user_id", Integer),
            Col::required("kind", Text),
            Col::required("resource_id", Text),
            Col::required("credential_id", Integer),
            Col::required("summary_json", Text),
            Col::required("created_at", Integer),
            Col::required("updated_at", Integer),
        ],
        indexes: &[
            IndexSpec {
                name: "uq_surface_bindings_resource",
                columns: &["provider_id", "owner_user_id", "kind", "resource_id"],
                unique: true,
            },
            IndexSpec {
                name: "ix_surface_bindings_list",
                columns: &["provider_id", "owner_user_id", "kind", "created_at", "id"],
                unique: false,
            },
        ],
    },
];
