#!/usr/bin/env python3
"""Prepare the pinned OHOS toolchain or apply it to a disposable build checkout."""
import argparse
import json
import os
from pathlib import Path
import re
import subprocess
import tomllib

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--phase", choices=("toolchain", "workspace", "all"), default="all")
phase = parser.parse_args().phase
root = Path.cwd()
source = Path(os.environ["OHOS_TAURI_SOURCES"]).resolve()
pins = json.loads((root / "scripts/ohos/tauri-pins.json").read_text())
marker = source / "gproxy-pins.json"

if phase in ("toolchain", "all"):
    for name, pin in pins.items():
        checkout = source / name
        subprocess.run(["git", "init", str(checkout)], check=True)
        subprocess.run(["git", "-C", str(checkout), "remote", "add", "origin",
                        f"https://github.com/{pin['repository']}.git"], check=True)
        subprocess.run(["git", "-C", str(checkout), "fetch", "--depth", "1", "origin", pin["revision"]], check=True)
        subprocess.run(["git", "-C", str(checkout), "checkout", "--detach", "FETCH_HEAD"], check=True)
    # Match the Ability revision in Tauri's own upstream lockfile.
    for checkout in (source / "tauri", source / "wry", source / "tao"):
        for manifest in checkout.rglob("Cargo.toml"):
            text = manifest.read_text().replace(
                'git = "https://github.com/harmony-contrib/openharmony-ability.git"',
                'git = "https://github.com/harmony-contrib/openharmony-ability.git", rev = "' + pins["ability"]["revision"] + '"')
            manifest.write_text(text)
    upstream = source / "tauri/Cargo.toml"
    text = upstream.read_text()
    for name in ("wry", "tao", "cargo-mobile2"):
        text = re.sub(rf'^{name} = .*$', f'{name} = {{ path = "{source / name}" }}', text, flags=re.MULTILINE)
    upstream.write_text(text)
    # Huawei's SDK has native directly below openharmony, without an API subdir.
    env_file = source / "cargo-mobile2/src/open_harmony/env.rs"
    text = env_file.read_text()
    old = '''self.ohos_home
                .parent()
                .unwrap()
                .parent()
                .unwrap()
                .parent()
                .unwrap()
                .as_os_str()
                .to_os_string()'''
    if old not in text:
        raise ValueError("Upstream OpenHarmony SDK layout helper changed")
    env_file.write_text(text.replace(old, 'std::env::var_os("DEVECO_SDK_HOME").expect("DEVECO_SDK_HOME is required")'))
    marker.write_text(json.dumps(pins, indent=2) + "\n")

if phase in ("workspace", "all"):
    if json.loads(marker.read_text()) != pins:
        raise ValueError("The OHOS toolchain image does not match tauri-pins.json")
    patches = {}
    for manifest in (source / "tauri/crates").glob("*/Cargo.toml"):
        name = tomllib.loads(manifest.read_text()).get("package", {}).get("name", "")
        if name.startswith("tauri"):
            patches[name] = manifest.parent
    for name in ("wry", "tao", "cargo-mobile2"):
        patches[name] = source / name
    manifest = root / "Cargo.toml"
    text = manifest.read_text()
    for name in ("tauri", "tauri-build"):
        text = re.sub(rf'^{name} = .*$', f'{name} = {{ path = "{patches[name]}" }}', text, count=1, flags=re.MULTILINE)
    # Desktop plugins require stable Tauri 2.12 and are not part of an OHOS app.
    host = root / "crates/gproxy-host-tauri/Cargo.toml"
    host_text = host.read_text()
    for name in ("tauri-plugin-dialog", "tauri-plugin-single-instance"):
        host_text = re.sub(rf'^{name} = .*\n', '', host_text, flags=re.MULTILINE)
    host.write_text(host_text + '\n[target.\'cfg(target_env = "ohos")\'.dependencies]\nnapi-ohos = "=1.2.0"\nnapi-derive-ohos = "=1.2.0"\n')
    text += '\n# OHOS-only dependency overlay, generated by scripts/ohos/prepare-tauri.py.\n'
    for name, path in patches.items():
        text += f'{name} = {{ path = "{path}" }}\n'
    manifest.write_text(text)
print(f"Prepared OHOS {phase} at {source}")
