#!/usr/bin/env python3
"""Apply the preinstalled OHOS dependency overlay to a disposable build checkout."""
import tomllib
import json
import os
from pathlib import Path
import re

root = Path.cwd()
source = Path(os.environ["OHOS_TAURI_SOURCES"]).resolve()
pins = json.loads((root / "scripts/ohos/tauri-pins.json").read_text())
marker = source / "tauri-harmony-pins.json"

if json.loads(marker.read_text()) != pins:
    raise ValueError("The OHOS toolchain image does not match tauri-pins.json")
patches = {}
for manifest in (source / "tauri/crates").glob("*/Cargo.toml"):
    name = tomllib.loads(manifest.read_text()).get("package", {}).get("name", "")
    if name.startswith("tauri"):
        patches[name] = manifest.parent
for name in ("wry", "tao", "cargo-mobile2"):
    patches[name] = source / name
manifest = root / "Cargo.toml"
text = manifest.read_text()
for name in ("tauri", "tauri-build"):
    text = re.sub(rf'^{name} = .*$', f'{name} = {{ path = "{patches[name]}" }}', text, count=1, flags=re.MULTILINE)
# Desktop plugins require stable Tauri 2.12 and are not part of an OHOS app.
host = root / "crates/gproxy-host-tauri/Cargo.toml"
host_text = host.read_text()
# HAPs load only the shared library. Emitting an rlib alongside it disables LTO.
host_text = host_text.replace('crate-type = ["lib", "cdylib"]', 'crate-type = ["cdylib"]')
# ohrs' initial build does not forward --lib. Do not let it build the desktop
# executable, which needs the rlib intentionally omitted from HAP builds.
host_text = host_text.replace('default-run = "gproxy-desktop"', 'autobins = false')
host_text = host_text.replace('[[bin]]\nname = "gproxy-desktop"\npath = "src/main.rs"\n\n', '')
for name in ("tauri-plugin-dialog", "tauri-plugin-single-instance"):
    host_text = re.sub(rf'^{name} = .*\n', '', host_text, flags=re.MULTILINE)
host.write_text(host_text + '\n[target.\'cfg(target_env = "ohos")\'.dependencies]\nnapi-ohos = "=1.2.0"\nnapi-derive-ohos = "=1.2.0"\n')
text += '\n# OHOS-only dependency overlay, generated by scripts/ohos/prepare-tauri.py.\n'
for name, path in patches.items():
    text += f'{name} = {{ path = "{path}" }}\n'
manifest.write_text(text)
print(f"Applied OHOS dependency overlay from {source}")
