/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppOrgsRouteImport } from './routes/_app/orgs'
import { Route as AppProvidersRouteImport } from './routes/_app/providers'
import { Route as AppRoutesRouteImport } from './routes/_app/routes'
import { Route as AppRulesRouteImport } from './routes/_app/rules'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppOrgsIndexRouteImport } from './routes/_app/orgs/index'
import { Route as AppOrgsOrgIdRouteImport } from './routes/_app/orgs/$orgId'
import { Route as AppOrgsNewRouteImport } from './routes/_app/orgs/new'
import { Route as AppPricingIndexRouteImport } from './routes/_app/pricing/index'
import { Route as AppProvidersIndexRouteImport } from './routes/_app/providers/index'
import { Route as AppProvidersProviderIdRouteImport } from './routes/_app/providers/$providerId'
import { Route as AppProvidersNewRouteImport } from './routes/_app/providers/new'
import { Route as AppRoutesIndexRouteImport } from './routes/_app/routes/index'
import { Route as AppRoutesRouteIdRouteImport } from './routes/_app/routes/$routeId'
import { Route as AppRoutesNewRouteImport } from './routes/_app/routes/new'
import { Route as AppRulesIndexRouteImport } from './routes/_app/rules/index'
import { Route as AppRulesRuleSetIdRouteImport } from './routes/_app/rules/$ruleSetId'
import { Route as AppRulesNewRouteImport } from './routes/_app/rules/new'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppUpdateIndexRouteImport } from './routes/_app/update/index'
import { Route as AppUsageIndexRouteImport } from './routes/_app/usage/index'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users/index'
import { Route as AppUsersUserIdRouteImport } from './routes/_app/users/$userId'
import { Route as AppUsersNewRouteImport } from './routes/_app/users/new'
import { Route as AppProvidersProviderIdIndexRouteImport } from './routes/_app/providers/$providerId/index'
import { Route as AppProvidersProviderIdCredentialsRouteImport } from './routes/_app/providers/$providerId/credentials'
import { Route as AppProvidersProviderIdModelsRouteImport } from './routes/_app/providers/$providerId/models'
import { Route as AppProvidersProviderIdRoutingRulesRouteImport } from './routes/_app/providers/$providerId/routing-rules'
import { Route as AppProvidersProviderIdRuleSetsRouteImport } from './routes/_app/providers/$providerId/rule-sets'
import { Route as AppProvidersProviderIdSettingsRouteImport } from './routes/_app/providers/$providerId/settings'
import { Route as PortalAccountKeysIndexRouteImport } from './routes/_portal/account/keys/index'
import { Route as PortalAccountLimitsIndexRouteImport } from './routes/_portal/account/limits/index'
import { Route as PortalAccountSecurityIndexRouteImport } from './routes/_portal/account/security/index'
import { Route as PortalAccountUsageIndexRouteImport } from './routes/_portal/account/usage/index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgsRoute = AppOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersRoute = AppProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutesRoute = AppRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgsIndexRoute = AppOrgsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgsRoute,
} as any)
const AppOrgsOrgIdRoute = AppOrgsOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => AppOrgsRoute,
} as any)
const AppOrgsNewRoute = AppOrgsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppOrgsRoute,
} as any)
const AppPricingIndexRoute = AppPricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersIndexRoute = AppProvidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProvidersRoute,
} as any)
const AppProvidersProviderIdRoute = AppProvidersProviderIdRouteImport.update({
  id: '/$providerId',
  path: '/$providerId',
  getParentRoute: () => AppProvidersRoute,
} as any)
const AppProvidersNewRoute = AppProvidersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProvidersRoute,
} as any)
const AppRoutesIndexRoute = AppRoutesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoutesRoute,
} as any)
const AppRoutesRouteIdRoute = AppRoutesRouteIdRouteImport.update({
  id: '/$routeId',
  path: '/$routeId',
  getParentRoute: () => AppRoutesRoute,
} as any)
const AppRoutesNewRoute = AppRoutesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoutesRoute,
} as any)
const AppRulesIndexRoute = AppRulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRulesRoute,
} as any)
const AppRulesRuleSetIdRoute = AppRulesRuleSetIdRouteImport.update({
  id: '/$ruleSetId',
  path: '/$ruleSetId',
  getParentRoute: () => AppRulesRoute,
} as any)
const AppRulesNewRoute = AppRulesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRulesRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppUpdateIndexRoute = AppUpdateIndexRouteImport.update({
  id: '/update/',
  path: '/update/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsageIndexRoute = AppUsageIndexRouteImport.update({
  id: '/usage/',
  path: '/usage/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppUsersNewRoute = AppUsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppProvidersProviderIdIndexRoute =
  AppProvidersProviderIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProvidersProviderIdRoute,
  } as any)
const AppProvidersProviderIdCredentialsRoute =
  AppProvidersProviderIdCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => AppProvidersProviderIdRoute,
  } as any)
const AppProvidersProviderIdModelsRoute =
  AppProvidersProviderIdModelsRouteImport.update({
    id: '/models',
    path: '/models',
    getParentRoute: () => AppProvidersProviderIdRoute,
  } as any)
const AppProvidersProviderIdRoutingRulesRoute =
  AppProvidersProviderIdRoutingRulesRouteImport.update({
    id: '/routing-rules',
    path: '/routing-rules',
    getParentRoute: () => AppProvidersProviderIdRoute,
  } as any)
const AppProvidersProviderIdRuleSetsRoute =
  AppProvidersProviderIdRuleSetsRouteImport.update({
    id: '/rule-sets',
    path: '/rule-sets',
    getParentRoute: () => AppProvidersProviderIdRoute,
  } as any)
const AppProvidersProviderIdSettingsRoute =
  AppProvidersProviderIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProvidersProviderIdRoute,
  } as any)
const PortalAccountKeysIndexRoute = PortalAccountKeysIndexRouteImport.update({
  id: '/account/keys/',
  path: '/account/keys/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccountLimitsIndexRoute =
  PortalAccountLimitsIndexRouteImport.update({
    id: '/account/limits/',
    path: '/account/limits/',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalAccountSecurityIndexRoute =
  PortalAccountSecurityIndexRouteImport.update({
    id: '/account/security/',
    path: '/account/security/',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalAccountUsageIndexRoute = PortalAccountUsageIndexRouteImport.update({
  id: '/account/usage/',
  path: '/account/usage/',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/orgs': typeof AppOrgsRouteWithChildren
  '/providers': typeof AppProvidersRouteWithChildren
  '/routes': typeof AppRoutesRouteWithChildren
  '/rules': typeof AppRulesRouteWithChildren
  '/users': typeof AppUsersRouteWithChildren
  '/orgs/$orgId': typeof AppOrgsOrgIdRoute
  '/orgs/new': typeof AppOrgsNewRoute
  '/providers/$providerId': typeof AppProvidersProviderIdRouteWithChildren
  '/providers/new': typeof AppProvidersNewRoute
  '/routes/$routeId': typeof AppRoutesRouteIdRoute
  '/routes/new': typeof AppRoutesNewRoute
  '/rules/$ruleSetId': typeof AppRulesRuleSetIdRoute
  '/rules/new': typeof AppRulesNewRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/users/new': typeof AppUsersNewRoute
  '/orgs/': typeof AppOrgsIndexRoute
  '/pricing/': typeof AppPricingIndexRoute
  '/providers/': typeof AppProvidersIndexRoute
  '/routes/': typeof AppRoutesIndexRoute
  '/rules/': typeof AppRulesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/update/': typeof AppUpdateIndexRoute
  '/usage/': typeof AppUsageIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/providers/$providerId/credentials': typeof AppProvidersProviderIdCredentialsRoute
  '/providers/$providerId/models': typeof AppProvidersProviderIdModelsRoute
  '/providers/$providerId/routing-rules': typeof AppProvidersProviderIdRoutingRulesRoute
  '/providers/$providerId/rule-sets': typeof AppProvidersProviderIdRuleSetsRoute
  '/providers/$providerId/settings': typeof AppProvidersProviderIdSettingsRoute
  '/providers/$providerId/': typeof AppProvidersProviderIdIndexRoute
  '/account/keys/': typeof PortalAccountKeysIndexRoute
  '/account/limits/': typeof PortalAccountLimitsIndexRoute
  '/account/security/': typeof PortalAccountSecurityIndexRoute
  '/account/usage/': typeof PortalAccountUsageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/orgs/$orgId': typeof AppOrgsOrgIdRoute
  '/orgs/new': typeof AppOrgsNewRoute
  '/providers/new': typeof AppProvidersNewRoute
  '/routes/$routeId': typeof AppRoutesRouteIdRoute
  '/routes/new': typeof AppRoutesNewRoute
  '/rules/$ruleSetId': typeof AppRulesRuleSetIdRoute
  '/rules/new': typeof AppRulesNewRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/users/new': typeof AppUsersNewRoute
  '/orgs': typeof AppOrgsIndexRoute
  '/pricing': typeof AppPricingIndexRoute
  '/providers': typeof AppProvidersIndexRoute
  '/routes': typeof AppRoutesIndexRoute
  '/rules': typeof AppRulesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/update': typeof AppUpdateIndexRoute
  '/usage': typeof AppUsageIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/providers/$providerId/credentials': typeof AppProvidersProviderIdCredentialsRoute
  '/providers/$providerId/models': typeof AppProvidersProviderIdModelsRoute
  '/providers/$providerId/routing-rules': typeof AppProvidersProviderIdRoutingRulesRoute
  '/providers/$providerId/rule-sets': typeof AppProvidersProviderIdRuleSetsRoute
  '/providers/$providerId/settings': typeof AppProvidersProviderIdSettingsRoute
  '/providers/$providerId': typeof AppProvidersProviderIdIndexRoute
  '/account/keys': typeof PortalAccountKeysIndexRoute
  '/account/limits': typeof PortalAccountLimitsIndexRoute
  '/account/security': typeof PortalAccountSecurityIndexRoute
  '/account/usage': typeof PortalAccountUsageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_portal': typeof PortalRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/orgs': typeof AppOrgsRouteWithChildren
  '/_app/providers': typeof AppProvidersRouteWithChildren
  '/_app/routes': typeof AppRoutesRouteWithChildren
  '/_app/rules': typeof AppRulesRouteWithChildren
  '/_app/users': typeof AppUsersRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/orgs/$orgId': typeof AppOrgsOrgIdRoute
  '/_app/orgs/new': typeof AppOrgsNewRoute
  '/_app/providers/$providerId': typeof AppProvidersProviderIdRouteWithChildren
  '/_app/providers/new': typeof AppProvidersNewRoute
  '/_app/routes/$routeId': typeof AppRoutesRouteIdRoute
  '/_app/routes/new': typeof AppRoutesNewRoute
  '/_app/rules/$ruleSetId': typeof AppRulesRuleSetIdRoute
  '/_app/rules/new': typeof AppRulesNewRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/users/new': typeof AppUsersNewRoute
  '/_app/orgs/': typeof AppOrgsIndexRoute
  '/_app/pricing/': typeof AppPricingIndexRoute
  '/_app/providers/': typeof AppProvidersIndexRoute
  '/_app/routes/': typeof AppRoutesIndexRoute
  '/_app/rules/': typeof AppRulesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/update/': typeof AppUpdateIndexRoute
  '/_app/usage/': typeof AppUsageIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_app/providers/$providerId/credentials': typeof AppProvidersProviderIdCredentialsRoute
  '/_app/providers/$providerId/models': typeof AppProvidersProviderIdModelsRoute
  '/_app/providers/$providerId/routing-rules': typeof AppProvidersProviderIdRoutingRulesRoute
  '/_app/providers/$providerId/rule-sets': typeof AppProvidersProviderIdRuleSetsRoute
  '/_app/providers/$providerId/settings': typeof AppProvidersProviderIdSettingsRoute
  '/_app/providers/$providerId/': typeof AppProvidersProviderIdIndexRoute
  '/_portal/account/keys/': typeof PortalAccountKeysIndexRoute
  '/_portal/account/limits/': typeof PortalAccountLimitsIndexRoute
  '/_portal/account/security/': typeof PortalAccountSecurityIndexRoute
  '/_portal/account/usage/': typeof PortalAccountUsageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/orgs'
    | '/providers'
    | '/routes'
    | '/rules'
    | '/users'
    | '/orgs/$orgId'
    | '/orgs/new'
    | '/providers/$providerId'
    | '/providers/new'
    | '/routes/$routeId'
    | '/routes/new'
    | '/rules/$ruleSetId'
    | '/rules/new'
    | '/users/$userId'
    | '/users/new'
    | '/orgs/'
    | '/pricing/'
    | '/providers/'
    | '/routes/'
    | '/rules/'
    | '/settings/'
    | '/update/'
    | '/usage/'
    | '/users/'
    | '/providers/$providerId/credentials'
    | '/providers/$providerId/models'
    | '/providers/$providerId/routing-rules'
    | '/providers/$providerId/rule-sets'
    | '/providers/$providerId/settings'
    | '/providers/$providerId/'
    | '/account/keys/'
    | '/account/limits/'
    | '/account/security/'
    | '/account/usage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/orgs/$orgId'
    | '/orgs/new'
    | '/providers/new'
    | '/routes/$routeId'
    | '/routes/new'
    | '/rules/$ruleSetId'
    | '/rules/new'
    | '/users/$userId'
    | '/users/new'
    | '/orgs'
    | '/pricing'
    | '/providers'
    | '/routes'
    | '/rules'
    | '/settings'
    | '/update'
    | '/usage'
    | '/users'
    | '/providers/$providerId/credentials'
    | '/providers/$providerId/models'
    | '/providers/$providerId/routing-rules'
    | '/providers/$providerId/rule-sets'
    | '/providers/$providerId/settings'
    | '/providers/$providerId'
    | '/account/keys'
    | '/account/limits'
    | '/account/security'
    | '/account/usage'
  id:
    | '__root__'
    | '/_app'
    | '/_portal'
    | '/login'
    | '/_app/orgs'
    | '/_app/providers'
    | '/_app/routes'
    | '/_app/rules'
    | '/_app/users'
    | '/_app/'
    | '/_app/orgs/$orgId'
    | '/_app/orgs/new'
    | '/_app/providers/$providerId'
    | '/_app/providers/new'
    | '/_app/routes/$routeId'
    | '/_app/routes/new'
    | '/_app/rules/$ruleSetId'
    | '/_app/rules/new'
    | '/_app/users/$userId'
    | '/_app/users/new'
    | '/_app/orgs/'
    | '/_app/pricing/'
    | '/_app/providers/'
    | '/_app/routes/'
    | '/_app/rules/'
    | '/_app/settings/'
    | '/_app/update/'
    | '/_app/usage/'
    | '/_app/users/'
    | '/_app/providers/$providerId/credentials'
    | '/_app/providers/$providerId/models'
    | '/_app/providers/$providerId/routing-rules'
    | '/_app/providers/$providerId/rule-sets'
    | '/_app/providers/$providerId/settings'
    | '/_app/providers/$providerId/'
    | '/_portal/account/keys/'
    | '/_portal/account/limits/'
    | '/_portal/account/security/'
    | '/_portal/account/usage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs': {
      id: '/_app/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof AppOrgsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/providers': {
      id: '/_app/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AppProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routes': {
      id: '/_app/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AppRoutesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rules': {
      id: '/_app/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs/': {
      id: '/_app/orgs/'
      path: '/'
      fullPath: '/orgs/'
      preLoaderRoute: typeof AppOrgsIndexRouteImport
      parentRoute: typeof AppOrgsRoute
    }
    '/_app/orgs/$orgId': {
      id: '/_app/orgs/$orgId'
      path: '/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof AppOrgsOrgIdRouteImport
      parentRoute: typeof AppOrgsRoute
    }
    '/_app/orgs/new': {
      id: '/_app/orgs/new'
      path: '/new'
      fullPath: '/orgs/new'
      preLoaderRoute: typeof AppOrgsNewRouteImport
      parentRoute: typeof AppOrgsRoute
    }
    '/_app/pricing/': {
      id: '/_app/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof AppPricingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/providers/': {
      id: '/_app/providers/'
      path: '/'
      fullPath: '/providers/'
      preLoaderRoute: typeof AppProvidersIndexRouteImport
      parentRoute: typeof AppProvidersRoute
    }
    '/_app/providers/$providerId': {
      id: '/_app/providers/$providerId'
      path: '/$providerId'
      fullPath: '/providers/$providerId'
      preLoaderRoute: typeof AppProvidersProviderIdRouteImport
      parentRoute: typeof AppProvidersRoute
    }
    '/_app/providers/new': {
      id: '/_app/providers/new'
      path: '/new'
      fullPath: '/providers/new'
      preLoaderRoute: typeof AppProvidersNewRouteImport
      parentRoute: typeof AppProvidersRoute
    }
    '/_app/routes/': {
      id: '/_app/routes/'
      path: '/'
      fullPath: '/routes/'
      preLoaderRoute: typeof AppRoutesIndexRouteImport
      parentRoute: typeof AppRoutesRoute
    }
    '/_app/routes/$routeId': {
      id: '/_app/routes/$routeId'
      path: '/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof AppRoutesRouteIdRouteImport
      parentRoute: typeof AppRoutesRoute
    }
    '/_app/routes/new': {
      id: '/_app/routes/new'
      path: '/new'
      fullPath: '/routes/new'
      preLoaderRoute: typeof AppRoutesNewRouteImport
      parentRoute: typeof AppRoutesRoute
    }
    '/_app/rules/': {
      id: '/_app/rules/'
      path: '/'
      fullPath: '/rules/'
      preLoaderRoute: typeof AppRulesIndexRouteImport
      parentRoute: typeof AppRulesRoute
    }
    '/_app/rules/$ruleSetId': {
      id: '/_app/rules/$ruleSetId'
      path: '/$ruleSetId'
      fullPath: '/rules/$ruleSetId'
      preLoaderRoute: typeof AppRulesRuleSetIdRouteImport
      parentRoute: typeof AppRulesRoute
    }
    '/_app/rules/new': {
      id: '/_app/rules/new'
      path: '/new'
      fullPath: '/rules/new'
      preLoaderRoute: typeof AppRulesNewRouteImport
      parentRoute: typeof AppRulesRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/update/': {
      id: '/_app/update/'
      path: '/update'
      fullPath: '/update/'
      preLoaderRoute: typeof AppUpdateIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usage/': {
      id: '/_app/usage/'
      path: '/usage'
      fullPath: '/usage/'
      preLoaderRoute: typeof AppUsageIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/users/new': {
      id: '/_app/users/new'
      path: '/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AppUsersNewRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/providers/$providerId/': {
      id: '/_app/providers/$providerId/'
      path: '/'
      fullPath: '/providers/$providerId/'
      preLoaderRoute: typeof AppProvidersProviderIdIndexRouteImport
      parentRoute: typeof AppProvidersProviderIdRoute
    }
    '/_app/providers/$providerId/credentials': {
      id: '/_app/providers/$providerId/credentials'
      path: '/credentials'
      fullPath: '/providers/$providerId/credentials'
      preLoaderRoute: typeof AppProvidersProviderIdCredentialsRouteImport
      parentRoute: typeof AppProvidersProviderIdRoute
    }
    '/_app/providers/$providerId/models': {
      id: '/_app/providers/$providerId/models'
      path: '/models'
      fullPath: '/providers/$providerId/models'
      preLoaderRoute: typeof AppProvidersProviderIdModelsRouteImport
      parentRoute: typeof AppProvidersProviderIdRoute
    }
    '/_app/providers/$providerId/routing-rules': {
      id: '/_app/providers/$providerId/routing-rules'
      path: '/routing-rules'
      fullPath: '/providers/$providerId/routing-rules'
      preLoaderRoute: typeof AppProvidersProviderIdRoutingRulesRouteImport
      parentRoute: typeof AppProvidersProviderIdRoute
    }
    '/_app/providers/$providerId/rule-sets': {
      id: '/_app/providers/$providerId/rule-sets'
      path: '/rule-sets'
      fullPath: '/providers/$providerId/rule-sets'
      preLoaderRoute: typeof AppProvidersProviderIdRuleSetsRouteImport
      parentRoute: typeof AppProvidersProviderIdRoute
    }
    '/_app/providers/$providerId/settings': {
      id: '/_app/providers/$providerId/settings'
      path: '/settings'
      fullPath: '/providers/$providerId/settings'
      preLoaderRoute: typeof AppProvidersProviderIdSettingsRouteImport
      parentRoute: typeof AppProvidersProviderIdRoute
    }
    '/_portal/account/keys/': {
      id: '/_portal/account/keys/'
      path: '/account/keys'
      fullPath: '/account/keys/'
      preLoaderRoute: typeof PortalAccountKeysIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/account/limits/': {
      id: '/_portal/account/limits/'
      path: '/account/limits'
      fullPath: '/account/limits/'
      preLoaderRoute: typeof PortalAccountLimitsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/account/security/': {
      id: '/_portal/account/security/'
      path: '/account/security'
      fullPath: '/account/security/'
      preLoaderRoute: typeof PortalAccountSecurityIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/account/usage/': {
      id: '/_portal/account/usage/'
      path: '/account/usage'
      fullPath: '/account/usage/'
      preLoaderRoute: typeof PortalAccountUsageIndexRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface AppOrgsRouteChildren {
  AppOrgsOrgIdRoute: typeof AppOrgsOrgIdRoute
  AppOrgsNewRoute: typeof AppOrgsNewRoute
  AppOrgsIndexRoute: typeof AppOrgsIndexRoute
}

const AppOrgsRouteChildren: AppOrgsRouteChildren = {
  AppOrgsOrgIdRoute: AppOrgsOrgIdRoute,
  AppOrgsNewRoute: AppOrgsNewRoute,
  AppOrgsIndexRoute: AppOrgsIndexRoute,
}

const AppOrgsRouteWithChildren =
  AppOrgsRoute._addFileChildren(AppOrgsRouteChildren)

interface AppProvidersProviderIdRouteChildren {
  AppProvidersProviderIdCredentialsRoute: typeof AppProvidersProviderIdCredentialsRoute
  AppProvidersProviderIdModelsRoute: typeof AppProvidersProviderIdModelsRoute
  AppProvidersProviderIdRoutingRulesRoute: typeof AppProvidersProviderIdRoutingRulesRoute
  AppProvidersProviderIdRuleSetsRoute: typeof AppProvidersProviderIdRuleSetsRoute
  AppProvidersProviderIdSettingsRoute: typeof AppProvidersProviderIdSettingsRoute
  AppProvidersProviderIdIndexRoute: typeof AppProvidersProviderIdIndexRoute
}

const AppProvidersProviderIdRouteChildren: AppProvidersProviderIdRouteChildren =
  {
    AppProvidersProviderIdCredentialsRoute:
      AppProvidersProviderIdCredentialsRoute,
    AppProvidersProviderIdModelsRoute: AppProvidersProviderIdModelsRoute,
    AppProvidersProviderIdRoutingRulesRoute:
      AppProvidersProviderIdRoutingRulesRoute,
    AppProvidersProviderIdRuleSetsRoute: AppProvidersProviderIdRuleSetsRoute,
    AppProvidersProviderIdSettingsRoute: AppProvidersProviderIdSettingsRoute,
    AppProvidersProviderIdIndexRoute: AppProvidersProviderIdIndexRoute,
  }

const AppProvidersProviderIdRouteWithChildren =
  AppProvidersProviderIdRoute._addFileChildren(
    AppProvidersProviderIdRouteChildren,
  )

interface AppProvidersRouteChildren {
  AppProvidersProviderIdRoute: typeof AppProvidersProviderIdRouteWithChildren
  AppProvidersNewRoute: typeof AppProvidersNewRoute
  AppProvidersIndexRoute: typeof AppProvidersIndexRoute
}

const AppProvidersRouteChildren: AppProvidersRouteChildren = {
  AppProvidersProviderIdRoute: AppProvidersProviderIdRouteWithChildren,
  AppProvidersNewRoute: AppProvidersNewRoute,
  AppProvidersIndexRoute: AppProvidersIndexRoute,
}

const AppProvidersRouteWithChildren = AppProvidersRoute._addFileChildren(
  AppProvidersRouteChildren,
)

interface AppRoutesRouteChildren {
  AppRoutesRouteIdRoute: typeof AppRoutesRouteIdRoute
  AppRoutesNewRoute: typeof AppRoutesNewRoute
  AppRoutesIndexRoute: typeof AppRoutesIndexRoute
}

const AppRoutesRouteChildren: AppRoutesRouteChildren = {
  AppRoutesRouteIdRoute: AppRoutesRouteIdRoute,
  AppRoutesNewRoute: AppRoutesNewRoute,
  AppRoutesIndexRoute: AppRoutesIndexRoute,
}

const AppRoutesRouteWithChildren = AppRoutesRoute._addFileChildren(
  AppRoutesRouteChildren,
)

interface AppRulesRouteChildren {
  AppRulesRuleSetIdRoute: typeof AppRulesRuleSetIdRoute
  AppRulesNewRoute: typeof AppRulesNewRoute
  AppRulesIndexRoute: typeof AppRulesIndexRoute
}

const AppRulesRouteChildren: AppRulesRouteChildren = {
  AppRulesRuleSetIdRoute: AppRulesRuleSetIdRoute,
  AppRulesNewRoute: AppRulesNewRoute,
  AppRulesIndexRoute: AppRulesIndexRoute,
}

const AppRulesRouteWithChildren = AppRulesRoute._addFileChildren(
  AppRulesRouteChildren,
)

interface AppUsersRouteChildren {
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppUsersNewRoute: typeof AppUsersNewRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppUsersRouteChildren: AppUsersRouteChildren = {
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppUsersNewRoute: AppUsersNewRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppUsersRouteWithChildren = AppUsersRoute._addFileChildren(
  AppUsersRouteChildren,
)

interface AppRouteChildren {
  AppOrgsRoute: typeof AppOrgsRouteWithChildren
  AppProvidersRoute: typeof AppProvidersRouteWithChildren
  AppRoutesRoute: typeof AppRoutesRouteWithChildren
  AppRulesRoute: typeof AppRulesRouteWithChildren
  AppUsersRoute: typeof AppUsersRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppPricingIndexRoute: typeof AppPricingIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppUpdateIndexRoute: typeof AppUpdateIndexRoute
  AppUsageIndexRoute: typeof AppUsageIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOrgsRoute: AppOrgsRouteWithChildren,
  AppProvidersRoute: AppProvidersRouteWithChildren,
  AppRoutesRoute: AppRoutesRouteWithChildren,
  AppRulesRoute: AppRulesRouteWithChildren,
  AppUsersRoute: AppUsersRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppPricingIndexRoute: AppPricingIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppUpdateIndexRoute: AppUpdateIndexRoute,
  AppUsageIndexRoute: AppUsageIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalRouteChildren {
  PortalAccountKeysIndexRoute: typeof PortalAccountKeysIndexRoute
  PortalAccountLimitsIndexRoute: typeof PortalAccountLimitsIndexRoute
  PortalAccountSecurityIndexRoute: typeof PortalAccountSecurityIndexRoute
  PortalAccountUsageIndexRoute: typeof PortalAccountUsageIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAccountKeysIndexRoute: PortalAccountKeysIndexRoute,
  PortalAccountLimitsIndexRoute: PortalAccountLimitsIndexRoute,
  PortalAccountSecurityIndexRoute: PortalAccountSecurityIndexRoute,
  PortalAccountUsageIndexRoute: PortalAccountUsageIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
